# Generated by Django 5.0.3 on 2024-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.JSONField()),
                ('sizes', models.JSONField()),
                ('photo', models.CharField(max_length=100)),
                ('preview', models.CharField(max_length=100)),
            ],
        ),
    ]
